name: Deploy to GitHub Pages

on:
  push:
    branches:
      - feature/customcursor  # Adjust if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Use the version of Node.js you need

    - name: Install dependencies
      run: npm install

    - name: Ensure Vite permissions
      run: chmod +x ./node_modules/.bin/vite

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        PAT: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      run: |
        set -x
        mkdir -p ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        pwd
        ls -la
        git remote -v
        git remote set-url origin git@github.com:devilcoder01/Hrx-Website.git
        git remote -v
        git checkout --orphan gh-pages
        git reset --hard
        ls --la
        cp -r dist/* .
        touch .nojekyll
        git status
        git add .
        git commit -m 'Deploy to GitHub Pages'
        ssh -T git@github.com
        git log --oneline -n 5
        git push origin gh-pages --force


    - name: Debug Info
      run: |
          ssh -vT git@github.com
          git remote -v
          git branch -a
    
    - name: Debug SSH key
      run: |
            ls -l ~/.ssh
            ssh-keygen -l -f ~/.ssh/id_rsa
            ssh -vT git@github.com